# Generated by Django 3.2.3 on 2022-03-24 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='datasheet',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.IntegerField(max_length=13)),
                ('date', models.DateField()),
                ('city', models.CharField(max_length=20)),
                ('areaName', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('vacination', models.CharField(max_length=20)),
                ('temperature', models.IntegerField()),
                ('spo2', models.IntegerField()),
            ],
        ),
    ]
