# Generated by Django 3.2.3 on 2022-03-24 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_datasheet_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasheet',
            name='spo2',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='datasheet',
            name='temperature',
            field=models.CharField(max_length=10),
        ),
    ]
