# Generated by Django 3.2.3 on 2022-03-24 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20220324_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasheet',
            name='vacination',
            field=models.CharField(max_length=40),
        ),
    ]
